package com.sistemas.seeder;

import com.sistemas.domain.Instructor;
import com.sistemas.service.InstructorService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration

public class InstructorSeeder {
    @Bean
    CommandLineRunner initInstructorDatabase(InstructorService instructorService) {
        return args -> {
            instructorService.create(Instructor.builder()
                    .name("Luis Gonzalo")
                    .paternalSurname("López")
                    .maternalSurname("García")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('P')
                    .instructorDedicationCode("D.E")
                    .cellphoneNumber("987654321")
                    .yearsOfTeaching(10)
                    .genderCode('M')
                    .password("clave0001")
                    .homePhoneNumber("043524679")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Ana Patricia")
                    .paternalSurname("Pérez")
                    .maternalSurname("Sánchez")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654322")
                    .yearsOfTeaching(7)
                    .genderCode('F')
                    .password("clave0002")
                    .homePhoneNumber("044612345")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("José Ramón")
                    .paternalSurname("Rodríguez")
                    .maternalSurname("Martínez")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('X')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654323")
                    .yearsOfTeaching(5)
                    .genderCode('M')
                    .password("clave0003")
                    .homePhoneNumber("054735182")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("María Gabriela")
                    .paternalSurname("Gómez")
                    .maternalSurname("Hernández")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('P')
                    .instructorDedicationCode("D.E")
                    .cellphoneNumber("987654324")
                    .yearsOfTeaching(15)
                    .genderCode('F')
                    .password("clave0004")
                    .homePhoneNumber("064421890")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Raúl Mauricio")
                    .paternalSurname("Martínez")
                    .maternalSurname("Fernández")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('X')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654325")
                    .yearsOfTeaching(2)
                    .genderCode('M')
                    .password("clave0005")
                    .homePhoneNumber("073328145")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Juliana Raquel")
                    .paternalSurname("Ruiz")
                    .maternalSurname("Gómez")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654326")
                    .yearsOfTeaching(8)
                    .genderCode('F')
                    .password("clave0006")
                    .homePhoneNumber("056439872")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Juan Luis")
                    .paternalSurname("Vázquez")
                    .maternalSurname("Torres")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654327")
                    .yearsOfTeaching(6)
                    .genderCode('M')
                    .password("clave0007")
                    .homePhoneNumber("041783920")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("María Mercedes")
                    .paternalSurname("Méndez")
                    .maternalSurname("Castro")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('P')
                    .instructorDedicationCode("D.E")
                    .cellphoneNumber("987654328")
                    .yearsOfTeaching(12)
                    .genderCode('F')
                    .password("clave0008")
                    .homePhoneNumber("065912384")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Carlos Santiago")
                    .paternalSurname("Soto")
                    .maternalSurname("Ramos")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('X')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654329")
                    .yearsOfTeaching(4)
                    .genderCode('M')
                    .password("clave0009")
                    .homePhoneNumber("072345678")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Ana María")
                    .paternalSurname("Torres")
                    .maternalSurname("Molina")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654330")
                    .yearsOfTeaching(9)
                    .genderCode('F')
                    .password("clave0010")
                    .homePhoneNumber("048394726")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Javier Roberto")
                    .paternalSurname("Ríos")
                    .maternalSurname("Reyes")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('P')
                    .instructorDedicationCode("D.E")
                    .cellphoneNumber("987654331")
                    .yearsOfTeaching(11)
                    .genderCode('M')
                    .password("clave0011")
                    .homePhoneNumber("066485293")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("José Omar")
                    .paternalSurname("Ortega")
                    .maternalSurname("Ortiz")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('X')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654332")
                    .yearsOfTeaching(3)
                    .genderCode('M')
                    .password("clave0012")
                    .homePhoneNumber("042871536")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Claudia María")
                    .paternalSurname("Castro")
                    .maternalSurname("Morales")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('P')
                    .instructorDedicationCode("D.E")
                    .cellphoneNumber("987654333")
                    .yearsOfTeaching(14)
                    .genderCode('F')
                    .password("clave0013")
                    .homePhoneNumber("047654839")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("José Héctor")
                    .paternalSurname("Hernández")
                    .maternalSurname("Jiménez")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654334")
                    .yearsOfTeaching(6)
                    .genderCode('M')
                    .password("clave0014")
                    .homePhoneNumber("074123654")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Ana Lucía")
                    .paternalSurname("Jiménez")
                    .maternalSurname("López")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654335")
                    .yearsOfTeaching(10)
                    .genderCode('F')
                    .password("clave0015")
                    .homePhoneNumber("067398412")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Jorge Nicolás")
                    .paternalSurname("Navarro")
                    .maternalSurname("Cruz")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('X')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654336")
                    .yearsOfTeaching(1)
                    .genderCode('M')
                    .password("clave0016")
                    .homePhoneNumber("045932781")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Rosa Carolina")
                    .paternalSurname("Campos")
                    .maternalSurname("Vega")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('P')
                    .instructorDedicationCode("D.E")
                    .cellphoneNumber("987654337")
                    .yearsOfTeaching(13)
                    .genderCode('F')
                    .password("clave0017")
                    .homePhoneNumber("046781245")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Juan Pablo")
                    .paternalSurname("Paredes")
                    .maternalSurname("Romero")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654338")
                    .yearsOfTeaching(7)
                    .genderCode('M')
                    .password("clave0018")
                    .homePhoneNumber("063823190")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Carolina María")
                    .paternalSurname("Moreno")
                    .maternalSurname("Silva")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Maestría")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('C')
                    .instructorCategoryCode('X')
                    .instructorDedicationCode("T.P")
                    .cellphoneNumber("987654339")
                    .yearsOfTeaching(4)
                    .genderCode('F')
                    .password("clave0019")
                    .homePhoneNumber("049734865")
                    .build());

            instructorService.create(Instructor.builder()
                    .name("Alberto Emilio")
                    .paternalSurname("Fernández")
                    .maternalSurname("Espinoza")
                    .profession("INGENIERO DE SISTEMAS E INFORMATICA")
                    .maxAcademicDegree("Doctorado")
                    .academicDepartment("CIVIL Y SISTEMAS")
                    .instructorConditionCode('N')
                    .instructorCategoryCode('A')
                    .instructorDedicationCode("T.C")
                    .cellphoneNumber("987654340")
                    .yearsOfTeaching(9)
                    .genderCode('M')
                    .password("clave0020")
                    .homePhoneNumber("049182865")
                    .build());
        };
    }
}
